site_name: CME 193 – Scientific Python (Autumn 2025)
site_description: Stanford CME 193 – Introduction to Scientific Python (Autumn 2025)
site_author: Tianyu Du

# If you host on GitHub, set this later to your repo URL to enable "Edit on GitHub" links
# repo_url: https://github.com/<org-or-user>/<repo>

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Docs are already under ./docs
docs_dir: docs

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Homework: homework.md
  - Google Colab: google-colab.md
  - Software: software.md
  - Local Jupyter: local-jupyter.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

strict: true