title: "CME 193 – Scientific Python (Autumn 2025)"
description: "Stanford CME 193 – Introduction to Scientific Python (Autumn 2025)"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: ""
baseurl: ""

just_the_docs:
  search_enabled: true